[package]
name = "dxe_readiness_capture"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
cfg-if = { workspace = true }
linked_list_allocator = "0.10.6"
log = { workspace = true }
patina = { workspace = true }
patina_stacktrace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spin = { workspace = true }
uefi = { version = "0.40.0", features = ["alloc", "logger", "global_allocator"] }

[features]
ci_features = []
default = []
x64 = []
aarch64 = []
uefishell = []